// Automatically generated - DO NOT EDIT!!!
// Generated by templatesWithClass Sun Jun 01 20:39:36 EDT 2014
package tictac;  // line 1: 0-35

public class CompilerHelper {

	public static String escapeMethod() {
		StringBuilder _twcOut = new StringBuilder();
		_twcOut.append("\n"); // line 4: 0-0
		_twcOut.append("    // how's this for eating one's own dogfood?"); // line 5: 0-47
		_twcOut.append("\n"); // line 5: 47-47
		_twcOut.append("    // this method is based upon Android's Html.withinStyle() method licensed"); // line 6: 0-77
		_twcOut.append("\n"); // line 6: 77-77
		_twcOut.append("    // under the Apache 2.0 license, retrieved on June 1, 2014 from"); // line 7: 0-67
		_twcOut.append("\n"); // line 7: 67-67
		_twcOut.append("    // http://grepcode.com/file_/repository.grepcode.com/java/ext/com.google.android/android/4.4.2_r1/android/text/Html.java/?v=source"); // line 8: 0-134
		_twcOut.append("\n"); // line 8: 134-134
		_twcOut.append("    // License available at http://www.apache.org/licenses/LICENSE-2.0"); // line 9: 0-70
		_twcOut.append("\n"); // line 9: 70-70
		_twcOut.append("    private static String escape(Object o) {"); // line 10: 0-44
		_twcOut.append("\n"); // line 10: 44-44
		_twcOut.append("        if (o == null) return \"\";"); // line 11: 0-33
		_twcOut.append("\n"); // line 11: 33-33
		_twcOut.append("        String text = o.toString();"); // line 12: 0-35
		_twcOut.append("\n"); // line 12: 35-35
		_twcOut.append("        StringBuilder out = new StringBuilder();"); // line 13: 0-48
		_twcOut.append("\n"); // line 13: 48-48
		_twcOut.append("        int end = text.length();"); // line 14: 0-32
		_twcOut.append("\n"); // line 14: 32-32
		_twcOut.append("        for (int i = 0; i < end; i++) {"); // line 15: 0-39
		_twcOut.append("\n"); // line 15: 39-39
		_twcOut.append("            char c = text.charAt(i);"); // line 16: 0-36
		_twcOut.append("\n"); // line 16: 36-36
		_twcOut.append("\n"); // line 17: 0-0
		_twcOut.append("            if (c == '<') {"); // line 18: 0-27
		_twcOut.append("\n"); // line 18: 27-27
		_twcOut.append("                out.append(\"&lt;\");"); // line 19: 0-35
		_twcOut.append("\n"); // line 19: 35-35
		_twcOut.append("            } else if (c == '>') {"); // line 20: 0-34
		_twcOut.append("\n"); // line 20: 34-34
		_twcOut.append("                out.append(\"&gt;\");"); // line 21: 0-35
		_twcOut.append("\n"); // line 21: 35-35
		_twcOut.append("            } else if (c == '&') {"); // line 22: 0-34
		_twcOut.append("\n"); // line 22: 34-34
		_twcOut.append("                out.append(\"&amp;\");"); // line 23: 0-36
		_twcOut.append("\n"); // line 23: 36-36
		_twcOut.append("            } else if (c >= 0xD800 && c <= 0xDFFF) {"); // line 24: 0-52
		_twcOut.append("\n"); // line 24: 52-52
		_twcOut.append("                if (c < 0xDC00 && i + 1 < end) {"); // line 25: 0-48
		_twcOut.append("\n"); // line 25: 48-48
		_twcOut.append("                    char d = text.charAt(i + 1);"); // line 26: 0-48
		_twcOut.append("\n"); // line 26: 48-48
		_twcOut.append("                    if (d >= 0xDC00 && d <= 0xDFFF) {"); // line 27: 0-53
		_twcOut.append("\n"); // line 27: 53-53
		_twcOut.append("                        i++;"); // line 28: 0-28
		_twcOut.append("\n"); // line 28: 28-28
		_twcOut.append("                        int codepoint = 0x010000 | (int) c - 0xD800 << 10 | (int) d - 0xDC00;"); // line 29: 0-93
		_twcOut.append("\n"); // line 29: 93-93
		_twcOut.append("                        out.append(\"&#\").append(codepoint).append(\";\");"); // line 30: 0-71
		_twcOut.append("\n"); // line 30: 71-71
		_twcOut.append("                    }"); // line 31: 0-21
		_twcOut.append("\n"); // line 31: 21-21
		_twcOut.append("                }"); // line 32: 0-17
		_twcOut.append("\n"); // line 32: 17-17
		_twcOut.append("            } else if (c > 0x7E || c < ' ') {"); // line 33: 0-45
		_twcOut.append("\n"); // line 33: 45-45
		_twcOut.append("                out.append(\"&#\").append((int) c).append(\";\");"); // line 34: 0-61
		_twcOut.append("\n"); // line 34: 61-61
		_twcOut.append("            } else if (c == ' ') {"); // line 35: 0-34
		_twcOut.append("\n"); // line 35: 34-34
		_twcOut.append("                while (i + 1 < end && text.charAt(i + 1) == ' ') {"); // line 36: 0-66
		_twcOut.append("\n"); // line 36: 66-66
		_twcOut.append("                    out.append(\"&nbsp;\");"); // line 37: 0-41
		_twcOut.append("\n"); // line 37: 41-41
		_twcOut.append("                    i++;"); // line 38: 0-24
		_twcOut.append("\n"); // line 38: 24-24
		_twcOut.append("                }"); // line 39: 0-17
		_twcOut.append("\n"); // line 39: 17-17
		_twcOut.append("\n"); // line 40: 0-0
		_twcOut.append("                out.append(' ');"); // line 41: 0-32
		_twcOut.append("\n"); // line 41: 32-32
		_twcOut.append("            } else {"); // line 42: 0-20
		_twcOut.append("\n"); // line 42: 20-20
		_twcOut.append("                out.append(c);"); // line 43: 0-30
		_twcOut.append("\n"); // line 43: 30-30
		_twcOut.append("            }"); // line 44: 0-13
		_twcOut.append("\n"); // line 44: 13-13
		_twcOut.append("        }"); // line 45: 0-9
		_twcOut.append("\n"); // line 45: 9-9
		_twcOut.append("        return out.toString();"); // line 46: 0-30
		_twcOut.append("\n"); // line 46: 30-30
		_twcOut.append("    }"); // line 47: 0-5
		_twcOut.append("\n"); // line 47: 5-5
		return _twcOut.toString();
	}

}
